//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.269
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.0.30319.1 自動產生。
// 
namespace Model.Schema.EIVO.B2B {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SellerInvoiceRoot {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Invoice")]
        public SellerInvoiceRootInvoice[] Invoice;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SellerInvoiceRootInvoice {
        
        /// <remarks/>
        public string InvoiceNumber;
        
        /// <remarks/>
        public string InvoiceDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InvoiceTime;
        
        /// <remarks/>
        public string SellerId;
        
        /// <remarks/>
        public string BuyerId;
        
        /// <remarks/>
        public string BuyerName;
        
        /// <remarks/>
        public string InvoiceType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceItem")]
        public SellerInvoiceRootInvoiceInvoiceItem[] InvoiceItem;
        
        /// <remarks/>
        public decimal SalesAmount;
        
        /// <remarks/>
        public byte TaxType;
        
        /// <remarks/>
        public decimal TaxAmount;
        
        /// <remarks/>
        public decimal TotalAmount;
        
        /// <remarks/>
        public object ExtraRemark;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SellerInvoiceRootInvoiceInvoiceItem {
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public decimal Quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Quantity2;
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Unit2;
        
        /// <remarks/>
        public decimal UnitPrice;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> UnitPrice2;
        
        /// <remarks/>
        public decimal Amount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Amount2;
        
        /// <remarks/>
        public decimal SequenceNumber;
        
        /// <remarks/>
        public string Remark;
    }
}
