#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DataEntity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EINVTurnkey2")]
	public partial class TurnKey2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TurnKey2DataContext() : 
				base(global::Model.Properties.Settings.Default.EINVTurnkey2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TurnKey2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TurnKey2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TurnKey2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TurnKey2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TURNKEY_USER_PROFILE> TURNKEY_USER_PROFILE
		{
			get
			{
				return this.GetTable<TURNKEY_USER_PROFILE>();
			}
		}
		
		public System.Data.Linq.Table<FROM_CONFIG> FROM_CONFIG
		{
			get
			{
				return this.GetTable<FROM_CONFIG>();
			}
		}
		
		public System.Data.Linq.Table<SCHEDULE_CONFIG> SCHEDULE_CONFIG
		{
			get
			{
				return this.GetTable<SCHEDULE_CONFIG>();
			}
		}
		
		public System.Data.Linq.Table<SIGN_CONFIG> SIGN_CONFIG
		{
			get
			{
				return this.GetTable<SIGN_CONFIG>();
			}
		}
		
		public System.Data.Linq.Table<TASK_CONFIG> TASK_CONFIG
		{
			get
			{
				return this.GetTable<TASK_CONFIG>();
			}
		}
		
		public System.Data.Linq.Table<TO_CONFIG> TO_CONFIG
		{
			get
			{
				return this.GetTable<TO_CONFIG>();
			}
		}
		
		public System.Data.Linq.Table<TURNKEY_MESSAGE_LOG> TURNKEY_MESSAGE_LOG
		{
			get
			{
				return this.GetTable<TURNKEY_MESSAGE_LOG>();
			}
		}
		
		public System.Data.Linq.Table<TURNKEY_MESSAGE_LOG_DETAIL> TURNKEY_MESSAGE_LOG_DETAIL
		{
			get
			{
				return this.GetTable<TURNKEY_MESSAGE_LOG_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<TURNKEY_SEQUENCE> TURNKEY_SEQUENCE
		{
			get
			{
				return this.GetTable<TURNKEY_SEQUENCE>();
			}
		}
		
		public System.Data.Linq.Table<TURNKEY_SYSEVENT_LOG> TURNKEY_SYSEVENT_LOG
		{
			get
			{
				return this.GetTable<TURNKEY_SYSEVENT_LOG>();
			}
		}
		
		public System.Data.Linq.Table<TURNKEY_TRANSPORT_CONFIG> TURNKEY_TRANSPORT_CONFIG
		{
			get
			{
				return this.GetTable<TURNKEY_TRANSPORT_CONFIG>();
			}
		}
		
		public System.Data.Linq.Table<V_Logs> V_Logs
		{
			get
			{
				return this.GetTable<V_Logs>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TURNKEY_USER_PROFILE")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TURNKEY_USER_PROFILE
	{
		
		private string _USER_ID;
		
		private string _USER_PASSWORD;
		
		private string _USER_ROLE;
		
		public TURNKEY_USER_PROFILE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this._USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_PASSWORD", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string USER_PASSWORD
		{
			get
			{
				return this._USER_PASSWORD;
			}
			set
			{
				if ((this._USER_PASSWORD != value))
				{
					this._USER_PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ROLE", DbType="VarChar(2)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string USER_ROLE
		{
			get
			{
				return this._USER_ROLE;
			}
			set
			{
				if ((this._USER_ROLE != value))
				{
					this._USER_ROLE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FROM_CONFIG")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class FROM_CONFIG
	{
		
		private string _TRANSPORT_ID;
		
		private string _TRANSPORT_PASSWORD;
		
		private string _PARTY_ID;
		
		private string _PARTY_DESCRIPTION;
		
		private string _ROUTING_ID;
		
		private string _ROUTING_DESCRIPTION;
		
		private string _SIGN_ID;
		
		private string _SUBSTITUTE_PARTY_ID;
		
		public FROM_CONFIG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSPORT_ID", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string TRANSPORT_ID
		{
			get
			{
				return this._TRANSPORT_ID;
			}
			set
			{
				if ((this._TRANSPORT_ID != value))
				{
					this._TRANSPORT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSPORT_PASSWORD", DbType="VarChar(45)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string TRANSPORT_PASSWORD
		{
			get
			{
				return this._TRANSPORT_PASSWORD;
			}
			set
			{
				if ((this._TRANSPORT_PASSWORD != value))
				{
					this._TRANSPORT_PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARTY_ID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string PARTY_ID
		{
			get
			{
				return this._PARTY_ID;
			}
			set
			{
				if ((this._PARTY_ID != value))
				{
					this._PARTY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARTY_DESCRIPTION", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string PARTY_DESCRIPTION
		{
			get
			{
				return this._PARTY_DESCRIPTION;
			}
			set
			{
				if ((this._PARTY_DESCRIPTION != value))
				{
					this._PARTY_DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROUTING_ID", DbType="VarChar(39)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string ROUTING_ID
		{
			get
			{
				return this._ROUTING_ID;
			}
			set
			{
				if ((this._ROUTING_ID != value))
				{
					this._ROUTING_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROUTING_DESCRIPTION", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string ROUTING_DESCRIPTION
		{
			get
			{
				return this._ROUTING_DESCRIPTION;
			}
			set
			{
				if ((this._ROUTING_DESCRIPTION != value))
				{
					this._ROUTING_DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIGN_ID", DbType="VarChar(4)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string SIGN_ID
		{
			get
			{
				return this._SIGN_ID;
			}
			set
			{
				if ((this._SIGN_ID != value))
				{
					this._SIGN_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBSTITUTE_PARTY_ID", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string SUBSTITUTE_PARTY_ID
		{
			get
			{
				return this._SUBSTITUTE_PARTY_ID;
			}
			set
			{
				if ((this._SUBSTITUTE_PARTY_ID != value))
				{
					this._SUBSTITUTE_PARTY_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SCHEDULE_CONFIG")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class SCHEDULE_CONFIG
	{
		
		private string _TASK;
		
		private string _ENABLE;
		
		private string _SCHEDULE_TYPE;
		
		private string _SCHEDULE_WEEK;
		
		private string _SCHEDULE_TIME;
		
		private string _SCHEDULE_PERIOD;
		
		private string _SCHEDULE_RANGE;
		
		public SCHEDULE_CONFIG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string TASK
		{
			get
			{
				return this._TASK;
			}
			set
			{
				if ((this._TASK != value))
				{
					this._TASK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENABLE", DbType="VarChar(1)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string ENABLE
		{
			get
			{
				return this._ENABLE;
			}
			set
			{
				if ((this._ENABLE != value))
				{
					this._ENABLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHEDULE_TYPE", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string SCHEDULE_TYPE
		{
			get
			{
				return this._SCHEDULE_TYPE;
			}
			set
			{
				if ((this._SCHEDULE_TYPE != value))
				{
					this._SCHEDULE_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHEDULE_WEEK", DbType="VarChar(15)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string SCHEDULE_WEEK
		{
			get
			{
				return this._SCHEDULE_WEEK;
			}
			set
			{
				if ((this._SCHEDULE_WEEK != value))
				{
					this._SCHEDULE_WEEK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHEDULE_TIME", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string SCHEDULE_TIME
		{
			get
			{
				return this._SCHEDULE_TIME;
			}
			set
			{
				if ((this._SCHEDULE_TIME != value))
				{
					this._SCHEDULE_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHEDULE_PERIOD", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string SCHEDULE_PERIOD
		{
			get
			{
				return this._SCHEDULE_PERIOD;
			}
			set
			{
				if ((this._SCHEDULE_PERIOD != value))
				{
					this._SCHEDULE_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHEDULE_RANGE", DbType="VarChar(15)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string SCHEDULE_RANGE
		{
			get
			{
				return this._SCHEDULE_RANGE;
			}
			set
			{
				if ((this._SCHEDULE_RANGE != value))
				{
					this._SCHEDULE_RANGE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SIGN_CONFIG")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class SIGN_CONFIG
	{
		
		private string _SIGN_ID;
		
		private string _SIGN_TYPE;
		
		private string _PFX_PATH;
		
		private string _SIGN_PASSWORD;
		
		public SIGN_CONFIG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIGN_ID", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string SIGN_ID
		{
			get
			{
				return this._SIGN_ID;
			}
			set
			{
				if ((this._SIGN_ID != value))
				{
					this._SIGN_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIGN_TYPE", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string SIGN_TYPE
		{
			get
			{
				return this._SIGN_TYPE;
			}
			set
			{
				if ((this._SIGN_TYPE != value))
				{
					this._SIGN_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PFX_PATH", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string PFX_PATH
		{
			get
			{
				return this._PFX_PATH;
			}
			set
			{
				if ((this._PFX_PATH != value))
				{
					this._PFX_PATH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIGN_PASSWORD", DbType="VarChar(60)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string SIGN_PASSWORD
		{
			get
			{
				return this._SIGN_PASSWORD;
			}
			set
			{
				if ((this._SIGN_PASSWORD != value))
				{
					this._SIGN_PASSWORD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TASK_CONFIG")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TASK_CONFIG
	{
		
		private string _CATEGORY_TYPE;
		
		private string _PROCESS_TYPE;
		
		private string _TASK;
		
		private string _SRC_PATH;
		
		private string _TARGET_PATH;
		
		private string _FILE_FORMAT;
		
		private string _VERSION;
		
		private string _ENCODING;
		
		private string _TRANS_CHINESE_DATE;
		
		public TASK_CONFIG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_TYPE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string CATEGORY_TYPE
		{
			get
			{
				return this._CATEGORY_TYPE;
			}
			set
			{
				if ((this._CATEGORY_TYPE != value))
				{
					this._CATEGORY_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESS_TYPE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string PROCESS_TYPE
		{
			get
			{
				return this._PROCESS_TYPE;
			}
			set
			{
				if ((this._PROCESS_TYPE != value))
				{
					this._PROCESS_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string TASK
		{
			get
			{
				return this._TASK;
			}
			set
			{
				if ((this._TASK != value))
				{
					this._TASK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SRC_PATH", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string SRC_PATH
		{
			get
			{
				return this._SRC_PATH;
			}
			set
			{
				if ((this._SRC_PATH != value))
				{
					this._SRC_PATH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARGET_PATH", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string TARGET_PATH
		{
			get
			{
				return this._TARGET_PATH;
			}
			set
			{
				if ((this._TARGET_PATH != value))
				{
					this._TARGET_PATH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_FORMAT", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string FILE_FORMAT
		{
			get
			{
				return this._FILE_FORMAT;
			}
			set
			{
				if ((this._FILE_FORMAT != value))
				{
					this._FILE_FORMAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="VarChar(5)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this._VERSION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENCODING", DbType="VarChar(15)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string ENCODING
		{
			get
			{
				return this._ENCODING;
			}
			set
			{
				if ((this._ENCODING != value))
				{
					this._ENCODING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_CHINESE_DATE", DbType="VarChar(1)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string TRANS_CHINESE_DATE
		{
			get
			{
				return this._TRANS_CHINESE_DATE;
			}
			set
			{
				if ((this._TRANS_CHINESE_DATE != value))
				{
					this._TRANS_CHINESE_DATE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TO_CONFIG")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TO_CONFIG
	{
		
		private string _PARTY_ID;
		
		private string _PARTY_DESCRIPTION;
		
		private string _ROUTING_ID;
		
		private string _ROUTING_DESCRIPTION;
		
		private string _FROM_PARTY_ID;
		
		public TO_CONFIG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARTY_ID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string PARTY_ID
		{
			get
			{
				return this._PARTY_ID;
			}
			set
			{
				if ((this._PARTY_ID != value))
				{
					this._PARTY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARTY_DESCRIPTION", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string PARTY_DESCRIPTION
		{
			get
			{
				return this._PARTY_DESCRIPTION;
			}
			set
			{
				if ((this._PARTY_DESCRIPTION != value))
				{
					this._PARTY_DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROUTING_ID", DbType="VarChar(39)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string ROUTING_ID
		{
			get
			{
				return this._ROUTING_ID;
			}
			set
			{
				if ((this._ROUTING_ID != value))
				{
					this._ROUTING_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROUTING_DESCRIPTION", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string ROUTING_DESCRIPTION
		{
			get
			{
				return this._ROUTING_DESCRIPTION;
			}
			set
			{
				if ((this._ROUTING_DESCRIPTION != value))
				{
					this._ROUTING_DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_PARTY_ID", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string FROM_PARTY_ID
		{
			get
			{
				return this._FROM_PARTY_ID;
			}
			set
			{
				if ((this._FROM_PARTY_ID != value))
				{
					this._FROM_PARTY_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TURNKEY_MESSAGE_LOG")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TURNKEY_MESSAGE_LOG
	{
		
		private string _SEQNO;
		
		private string _SUBSEQNO;
		
		private string _UUID;
		
		private string _MESSAGE_TYPE;
		
		private string _CATEGORY_TYPE;
		
		private string _PROCESS_TYPE;
		
		private string _FROM_PARTY_ID;
		
		private string _TO_PARTY_ID;
		
		private string _MESSAGE_DTS;
		
		private string _CHARACTER_COUNT;
		
		private string _STATUS;
		
		private string _IN_OUT_BOUND;
		
		private string _FROM_ROUTING_ID;
		
		private string _TO_ROUTING_ID;
		
		private string _INVOICE_IDENTIFIER;
		
		public TURNKEY_MESSAGE_LOG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQNO", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string SEQNO
		{
			get
			{
				return this._SEQNO;
			}
			set
			{
				if ((this._SEQNO != value))
				{
					this._SEQNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBSEQNO", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string SUBSEQNO
		{
			get
			{
				return this._SUBSEQNO;
			}
			set
			{
				if ((this._SUBSEQNO != value))
				{
					this._SUBSEQNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UUID", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string UUID
		{
			get
			{
				return this._UUID;
			}
			set
			{
				if ((this._UUID != value))
				{
					this._UUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE_TYPE", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string MESSAGE_TYPE
		{
			get
			{
				return this._MESSAGE_TYPE;
			}
			set
			{
				if ((this._MESSAGE_TYPE != value))
				{
					this._MESSAGE_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_TYPE", DbType="VarChar(5)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string CATEGORY_TYPE
		{
			get
			{
				return this._CATEGORY_TYPE;
			}
			set
			{
				if ((this._CATEGORY_TYPE != value))
				{
					this._CATEGORY_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESS_TYPE", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string PROCESS_TYPE
		{
			get
			{
				return this._PROCESS_TYPE;
			}
			set
			{
				if ((this._PROCESS_TYPE != value))
				{
					this._PROCESS_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_PARTY_ID", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string FROM_PARTY_ID
		{
			get
			{
				return this._FROM_PARTY_ID;
			}
			set
			{
				if ((this._FROM_PARTY_ID != value))
				{
					this._FROM_PARTY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_PARTY_ID", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string TO_PARTY_ID
		{
			get
			{
				return this._TO_PARTY_ID;
			}
			set
			{
				if ((this._TO_PARTY_ID != value))
				{
					this._TO_PARTY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE_DTS", DbType="VarChar(17)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string MESSAGE_DTS
		{
			get
			{
				return this._MESSAGE_DTS;
			}
			set
			{
				if ((this._MESSAGE_DTS != value))
				{
					this._MESSAGE_DTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARACTER_COUNT", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string CHARACTER_COUNT
		{
			get
			{
				return this._CHARACTER_COUNT;
			}
			set
			{
				if ((this._CHARACTER_COUNT != value))
				{
					this._CHARACTER_COUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(5)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_OUT_BOUND", DbType="VarChar(1)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string IN_OUT_BOUND
		{
			get
			{
				return this._IN_OUT_BOUND;
			}
			set
			{
				if ((this._IN_OUT_BOUND != value))
				{
					this._IN_OUT_BOUND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_ROUTING_ID", DbType="VarChar(39)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string FROM_ROUTING_ID
		{
			get
			{
				return this._FROM_ROUTING_ID;
			}
			set
			{
				if ((this._FROM_ROUTING_ID != value))
				{
					this._FROM_ROUTING_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_ROUTING_ID", DbType="VarChar(39)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string TO_ROUTING_ID
		{
			get
			{
				return this._TO_ROUTING_ID;
			}
			set
			{
				if ((this._TO_ROUTING_ID != value))
				{
					this._TO_ROUTING_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVOICE_IDENTIFIER", DbType="VarChar(30)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public string INVOICE_IDENTIFIER
		{
			get
			{
				return this._INVOICE_IDENTIFIER;
			}
			set
			{
				if ((this._INVOICE_IDENTIFIER != value))
				{
					this._INVOICE_IDENTIFIER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TURNKEY_MESSAGE_LOG_DETAIL")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TURNKEY_MESSAGE_LOG_DETAIL
	{
		
		private string _SEQNO;
		
		private string _SUBSEQNO;
		
		private string _PROCESS_DTS;
		
		private string _TASK;
		
		private string _STATUS;
		
		private string _FILENAME;
		
		private string _UUID;
		
		public TURNKEY_MESSAGE_LOG_DETAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQNO", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string SEQNO
		{
			get
			{
				return this._SEQNO;
			}
			set
			{
				if ((this._SEQNO != value))
				{
					this._SEQNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBSEQNO", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string SUBSEQNO
		{
			get
			{
				return this._SUBSEQNO;
			}
			set
			{
				if ((this._SUBSEQNO != value))
				{
					this._SUBSEQNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESS_DTS", DbType="VarChar(17)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string PROCESS_DTS
		{
			get
			{
				return this._PROCESS_DTS;
			}
			set
			{
				if ((this._PROCESS_DTS != value))
				{
					this._PROCESS_DTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string TASK
		{
			get
			{
				return this._TASK;
			}
			set
			{
				if ((this._TASK != value))
				{
					this._TASK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(5)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILENAME", DbType="VarChar(300)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string FILENAME
		{
			get
			{
				return this._FILENAME;
			}
			set
			{
				if ((this._FILENAME != value))
				{
					this._FILENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UUID", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string UUID
		{
			get
			{
				return this._UUID;
			}
			set
			{
				if ((this._UUID != value))
				{
					this._UUID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TURNKEY_SEQUENCE")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TURNKEY_SEQUENCE
	{
		
		private string _SEQUENCE;
		
		public TURNKEY_SEQUENCE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQUENCE", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string SEQUENCE
		{
			get
			{
				return this._SEQUENCE;
			}
			set
			{
				if ((this._SEQUENCE != value))
				{
					this._SEQUENCE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TURNKEY_SYSEVENT_LOG")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TURNKEY_SYSEVENT_LOG
	{
		
		private string _EVENTDTS;
		
		private string _PARTY_ID;
		
		private string _SEQNO;
		
		private string _SUBSEQNO;
		
		private string _ERRORCODE;
		
		private string _UUID;
		
		private string _INFORMATION1;
		
		private string _INFORMATION2;
		
		private string _INFORMATION3;
		
		private string _MESSAGE1;
		
		private string _MESSAGE2;
		
		private string _MESSAGE3;
		
		private string _MESSAGE4;
		
		private string _MESSAGE5;
		
		private string _MESSAGE6;
		
		public TURNKEY_SYSEVENT_LOG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVENTDTS", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string EVENTDTS
		{
			get
			{
				return this._EVENTDTS;
			}
			set
			{
				if ((this._EVENTDTS != value))
				{
					this._EVENTDTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARTY_ID", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string PARTY_ID
		{
			get
			{
				return this._PARTY_ID;
			}
			set
			{
				if ((this._PARTY_ID != value))
				{
					this._PARTY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQNO", DbType="VarChar(8)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string SEQNO
		{
			get
			{
				return this._SEQNO;
			}
			set
			{
				if ((this._SEQNO != value))
				{
					this._SEQNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBSEQNO", DbType="VarChar(5)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string SUBSEQNO
		{
			get
			{
				return this._SUBSEQNO;
			}
			set
			{
				if ((this._SUBSEQNO != value))
				{
					this._SUBSEQNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERRORCODE", DbType="VarChar(4)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string ERRORCODE
		{
			get
			{
				return this._ERRORCODE;
			}
			set
			{
				if ((this._ERRORCODE != value))
				{
					this._ERRORCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UUID", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string UUID
		{
			get
			{
				return this._UUID;
			}
			set
			{
				if ((this._UUID != value))
				{
					this._UUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFORMATION1", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string INFORMATION1
		{
			get
			{
				return this._INFORMATION1;
			}
			set
			{
				if ((this._INFORMATION1 != value))
				{
					this._INFORMATION1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFORMATION2", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string INFORMATION2
		{
			get
			{
				return this._INFORMATION2;
			}
			set
			{
				if ((this._INFORMATION2 != value))
				{
					this._INFORMATION2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFORMATION3", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string INFORMATION3
		{
			get
			{
				return this._INFORMATION3;
			}
			set
			{
				if ((this._INFORMATION3 != value))
				{
					this._INFORMATION3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE1", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string MESSAGE1
		{
			get
			{
				return this._MESSAGE1;
			}
			set
			{
				if ((this._MESSAGE1 != value))
				{
					this._MESSAGE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE2", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string MESSAGE2
		{
			get
			{
				return this._MESSAGE2;
			}
			set
			{
				if ((this._MESSAGE2 != value))
				{
					this._MESSAGE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE3", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string MESSAGE3
		{
			get
			{
				return this._MESSAGE3;
			}
			set
			{
				if ((this._MESSAGE3 != value))
				{
					this._MESSAGE3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE4", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string MESSAGE4
		{
			get
			{
				return this._MESSAGE4;
			}
			set
			{
				if ((this._MESSAGE4 != value))
				{
					this._MESSAGE4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE5", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string MESSAGE5
		{
			get
			{
				return this._MESSAGE5;
			}
			set
			{
				if ((this._MESSAGE5 != value))
				{
					this._MESSAGE5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE6", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public string MESSAGE6
		{
			get
			{
				return this._MESSAGE6;
			}
			set
			{
				if ((this._MESSAGE6 != value))
				{
					this._MESSAGE6 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TURNKEY_TRANSPORT_CONFIG")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TURNKEY_TRANSPORT_CONFIG
	{
		
		private string _TRANSPORT_ID;
		
		private string _TRANSPORT_PASSWORD;
		
		public TURNKEY_TRANSPORT_CONFIG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSPORT_ID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string TRANSPORT_ID
		{
			get
			{
				return this._TRANSPORT_ID;
			}
			set
			{
				if ((this._TRANSPORT_ID != value))
				{
					this._TRANSPORT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSPORT_PASSWORD", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string TRANSPORT_PASSWORD
		{
			get
			{
				return this._TRANSPORT_PASSWORD;
			}
			set
			{
				if ((this._TRANSPORT_PASSWORD != value))
				{
					this._TRANSPORT_PASSWORD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Logs")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class V_Logs
	{
		
		private string _SEQNO;
		
		private string _SUBSEQNO;
		
		private string _STATUS;
		
		private string _DocType;
		
		private string _TrackCode;
		
		private string _No;
		
		private System.Nullable<System.DateTime> _InvoiceDate;
		
		private System.Nullable<System.DateTime> _MESSAGE_DTS;
		
		public V_Logs()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQNO", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string SEQNO
		{
			get
			{
				return this._SEQNO;
			}
			set
			{
				if ((this._SEQNO != value))
				{
					this._SEQNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBSEQNO", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string SUBSEQNO
		{
			get
			{
				return this._SUBSEQNO;
			}
			set
			{
				if ((this._SUBSEQNO != value))
				{
					this._SUBSEQNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(5)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocType", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string DocType
		{
			get
			{
				return this._DocType;
			}
			set
			{
				if ((this._DocType != value))
				{
					this._DocType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackCode", DbType="VarChar(4)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string TrackCode
		{
			get
			{
				return this._TrackCode;
			}
			set
			{
				if ((this._TrackCode != value))
				{
					this._TrackCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="VarChar(16)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this._No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<System.DateTime> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this._InvoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE_DTS", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<System.DateTime> MESSAGE_DTS
		{
			get
			{
				return this._MESSAGE_DTS;
			}
			set
			{
				if ((this._MESSAGE_DTS != value))
				{
					this._MESSAGE_DTS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
