/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CDS_Document SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.DocumentDownloadQueue
	(
	DocID int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.DocumentDownloadQueue ADD CONSTRAINT
	PK_DocumentDownloadQueue PRIMARY KEY CLUSTERED 
	(
	DocID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.DocumentDownloadQueue ADD CONSTRAINT
	FK_DocumentDownloadQueue_CDS_Document FOREIGN KEY
	(
	DocID
	) REFERENCES dbo.CDS_Document
	(
	DocID
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.DocumentDownloadQueue SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.DocumentMappingQueue
	(
	DocID int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.DocumentMappingQueue ADD CONSTRAINT
	PK_DocumentMappingQueue PRIMARY KEY CLUSTERED 
	(
	DocID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.DocumentMappingQueue ADD CONSTRAINT
	FK_DocumentMappingQueue_CDS_Document FOREIGN KEY
	(
	DocID
	) REFERENCES dbo.CDS_Document
	(
	DocID
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.DocumentMappingQueue SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
